server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.gortoppgquyksjmneyry.supabase.co:6543/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mendes12155!}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:FocusFlow@2026#JWT$Segredo!MuitoSeguro}
jwt.expiration-ms=86400000

openai.api-key=${OPENAI_API_KEY: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}
openai.model=gpt-4o-mini